### ISSUE TITLE
"npm start validate" fails on untouched (fresh) fork

### ISSUE THREAD

**Issue by ghost** [kentcdodds/nps-utils#12]
Hi,
just wanted to add a neat feature for this repo but... validation fails on an untouched code.

- Operating system: macOS Sierra 10.12.3
- Node: v7.7.4
- Issue - failed tests: 
  - crossEnv as darwin: 
     - expect(value).toMatchSnapshot() - Received value does not match stored snapshot 1.
  - crossEnv as win32: 
     - expect(value).toMatchSnapshot() - Received value does not match stored snapshot 1.
- Dumpfrom: npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/dabrowskif/.nvm/v7.7.4/bin/node',
1 verbose cli   '/Users/dabrowskif/.nvm/v7.7.4/bin/npm',
1 verbose cli   'start',
1 verbose cli   'validate' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nps-utils@0.0.0-semantically-released~prestart: nps-utils@0.0.0-semantically-released
6 silly lifecycle nps-utils@0.0.0-semantically-released~prestart: no script for prestart, continuing
7 info lifecycle nps-utils@0.0.0-semantically-released~start: nps-utils@0.0.0-semantically-released
8 verbose lifecycle nps-utils@0.0.0-semantically-released~start: unsafe-perm in lifecycle true
9 verbose lifecycle nps-utils@0.0.0-semantically-released~start: PATH: /Users/dabrowskif/.nvm/v7.7.4/lib/node_modules/npm/bin/node-gyp-bin:/Users/dabrowskif/Documents/nps-utils/node_modules/.bin:/Users/dabrowskif/.nvm/v7.7.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/share/npm/bin
10 verbose lifecycle nps-utils@0.0.0-semantically-released~start: CWD: /Users/dabrowskif/Documents/nps-utils
11 silly lifecycle nps-utils@0.0.0-semantically-released~start: Args: [ '-c', 'nps "validate"' ]
12 silly lifecycle nps-utils@0.0.0-semantically-released~start: Returned: code: 1  signal: null
13 info lifecycle nps-utils@0.0.0-semantically-released~start: Failed to exec start script
14 verbose stack Error: nps-utils@0.0.0-semantically-released start: `nps "validate"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/dabrowskif/.nvm/v7.7.4/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/dabrowskif/.nvm/v7.7.4/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid nps-utils@0.0.0-semantically-released
16 verbose cwd /Users/dabrowskif/Documents/nps-utils
17 error Darwin 16.4.0
18 error argv "/Users/dabrowskif/.nvm/v7.7.4/bin/node" "/Users/dabrowskif/.nvm/v7.7.4/bin/npm" "start" "validate"
19 error node v7.7.4
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error nps-utils@0.0.0-semantically-released start: `nps "validate"`
22 error Exit status 1
23 error Failed at the nps-utils@0.0.0-semantically-released start script 'nps "validate"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the nps-utils package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nps "validate"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs nps-utils
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls nps-utils
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Apologies, but don't have time to dig what's happening there ;-/

**Comment by kentcdodds** [comment]
Hi. Thanks for trying things out. This doesn't give me enough information to know what the problem actually was. If you could paste the entire output from `npm start validate` that would be very helpful.

**Comment by ghost** [comment]
@kentcdodds sorry for no slow response. Here you go the dump of `npm start validate`:

<details>
<summary>output</summary>

```

> nps-utils@0.0.0-semantically-released start /Users/dabrowskif/Documents/nps-utils
> nps "validate"

nps executing: node node_modules/concurrently/src/main.js --kill-others-on-fail --prefix-colors "bgBlue.bold,bgMagenta.bold,bgGreen.bold" --prefix "[{name}]" --names "lint,build,test" 'nps lint' 'nps build' 'nps test'
[lint] nps executing: eslint .
[build] nps executing: rimraf dist && babel --copy-files --out-dir dist --ignore *.test.js src
[test] nps executing: jest --coverage
[build] src/index.js -> dist/index.js
[build] nps build exited with code 0
[lint] nps lint exited with code 0
[test]  FAIL  src/index.test.js
[test]   ● crossEnv as darwin
[test] 
[test]     expect(value).toMatchSnapshot()
[test]     
[test]     Received value does not match stored snapshot 1.
[test]     
[test]     - "node node_modules/cross-env/bin/cross-env.js NODE_ENV=test jest"
[test]     + "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest"
[test]       
[test]       at Object.<anonymous> (src/index.test.js:58:37)
[test] 
[test]   ● crossEnv as win32
[test] 
[test]     expect(value).toMatchSnapshot()
[test]     
[test]     Received value does not match stored snapshot 1.
[test]     
[test]     - "node node_modules/cross-env/bin/cross-env.js NODE_ENV=test jest"
[test]     + "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=test jest"
[test]       
[test]       at Object.<anonymous> (src/index.test.js:62:37)
[test] 
[test]   ✓ series as darwin (63ms)
[test]   ✓ series as win32 (11ms)
[test]   ✓ series.nps as darwin (9ms)
[test]   ✓ series.nps as win32 (12ms)
[test]   ✓ concurrent as darwin (9ms)
[test]   ✓ concurrent as win32 (9ms)
[test]   ✓ concurrent.nps as darwin (8ms)
[test]   ✓ concurrent.nps as win32 (9ms)
[test]   ✓ runInNewWindow as darwin (10ms)
[test]   ✓ runInNewWindow as win32 (8ms)
[test]   ✓ runInNewWindow.nps as darwin (9ms)
[test]   ✓ runInNewWindow.nps as win32 (10ms)
[test]   ✓ rimraf as darwin (7ms)
[test]   ✓ rimraf as win32 (7ms)
[test]   ✓ ifWindows as darwin (7ms)
[test]   ✓ ifWindows as win32 (7ms)
[test]   ✓ ifNotWindows as darwin (7ms)
[test]   ✓ ifNotWindows as win32 (7ms)
[test]   ✓ copy as darwin (7ms)
[test]   ✓ copy as win32 (9ms)
[test]   ✓ mkdirp as darwin (10ms)
[test]   ✓ mkdirp as win32 (8ms)
[test]   ✓ open as darwin (8ms)
[test]   ✓ open as win32 (7ms)
[test]   ✕ crossEnv as darwin (10ms)
[test]   ✕ crossEnv as win32 (7ms)
[test]   ✓ commonTags as darwin (7ms)
[test]   ✓ commonTags as win32 (8ms)
[test] 
[test] ----------|----------|----------|----------|----------|----------------|
[test] File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
[test] ----------|----------|----------|----------|----------|----------------|
[test] All files |      100 |    95.83 |      100 |      100 |                |
[test]  index.js |      100 |    95.83 |      100 |      100 |                |
[test] ----------|----------|----------|----------|----------|----------------|
[test] Jest: Coverage for branches (95.83%) does not meet global threshold (100%)
[test] Snapshot Summary
[test]  › 2 snapshot tests failed in 1 test suite. Inspect your code changes or run with `npm start -- -u` to update them.
[test] 
[test] Test Suites: 1 failed, 1 total
[test] Tests:       2 failed, 26 passed, 28 total
[test] Snapshots:   2 failed, 26 passed, 28 total
[test] Time:        0.841s, estimated 2s
[test] Ran all test suites.
[test] The script called "test" which runs "jest --coverage" failed with exit code 1 https://github.com/kentcdodds/nps/blob/v5.0.5/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
[test] nps test exited with code 1
```

</details>

**Comment by kentcdodds** [comment]
Are you sure you're on the latest of `master`? Oh, what it could also be is you have an outdated `cross-env` version. Could you reinstall all dependencies? Let me know.

**Comment by ghost** [comment]
@kentcdodds just cloned it again just to be sure ;-) Still same errors.

Version of cross-env: cross-env@3.2.4

**Comment by kentcdodds** [comment]
Could you look to see whether there's a file in `node_modules/cross-env/bin/cross-env.js`? There shouldn't be. It should be in `node_modules/cross-env/dist/bin/cross-env.js`.

**Comment by macklinu** [comment]
I just checked out this repo and was able to run the test and validate scripts successfully. Might be worth closing unless this can be reproduced?
